name: Build and Lint Vite Application 🚀

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier 🎨
        run: pnpm format

      - name: Run Linter 🧹
        run: pnpm lint

      - name: Run build 🏗️
        run: pnpm build